version: "2"
services:
  mongo:
    image: docker.io/mongo:4.0
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ~/.cache/cc-agency/db:/data/db:rw,z
    tty: true

  mongo-seed:
    build: ./mongo-seed
    volumes:
      - ./cc-agency.yml:/opt/cc-agency.yml:ro,z
      - ../cc_agency:/opt/cc-agency/cc_agency:ro,z
    command: "python3 -u -m cc_agency.tools.create_db_user -c /opt/cc-agency.yml --host mongo"
    links:
      - mongo
    tty: true
